### ISSUE TITLE
Test example not working on chrome ubuntu 16.04

### ISSUE THREAD

**Issue by JiancongWang** [rii-mango/Papaya#104]
Hi Sir, 
I downloaded the papaya repo on github and I tried to open the "tests/run_test_release.html". With chrome it fails to load the sample image and report the following error. I do some search online and it seems that chrome has blocked reading local files. I tried to open chrome with the -allow-file-access-from-files option and still no luck. 
On Firefox the example works normally.  

Error: There was a problem reading that file (sample_image.nii.gz):

Response status = 0
    at Object.<anonymous> (file:///home/jiancong/Downloads/rii-mango-Papaya-00ad6ba/release/current/standard/papaya.js:1410:40)
    at u (file:///home/jiancong/Downloads/rii-mango-Papaya-00ad6ba/release/current/standard/papaya.js:32:34)
    at Object.fireWith [as rejectWith] (file:///home/jiancong/Downloads/rii-mango-Papaya-00ad6ba/release/current/standard/papaya.js:33:299)
    at Object.d.(anonymous function) [as reject] (file:///home/jiancong/Downloads/rii-mango-Papaya-00ad6ba/release/current/standard/papaya.js:35:276)
    at XMLHttpRequest.string.responseType.f.onreadystatechange (file:///home/jiancong/Downloads/rii-mango-Papaya-00ad6ba/release/current/standard/papaya.js:1411:333)

**Comment by martinezmj** [comment]
You'll need to put it on a webserver to run that script -- you're right that there are security restrictions on reading local files.  If you want to test when not on a web server, try 'debug_local.html'.

**Comment by JiancongWang** [comment]
Thanks! I will check it out.
